<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "navidual"
 *
 * Auto generated by Extension Builder 2020-02-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Navidual',
    'description' => 'Individuelle Navigation, Orte- und Routenverwaltung.',
    'category' => 'plugin',
    'author' => 'Fabio Ciresa',
    'author_email' => 'fciresa@tsn.at',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
